config/routes.rb
Rails.application.routes.draw do
  get 'coordinates/new'
  post 'coordinates/create'
  get 'coordinates/update'
  post 'coordinates/destroy'
  post 'coordinates/index'
  post 'timelinks/create'
  post 'timelinks/destroy'
  get '/user', to: "worlds#index", :as => :user_root


  resources :worlds do
    resources :tags, only: [:create, :update]
    resources :cards do
      resources :taggings, only: [:create, :destroy]
    end
    resources :maps
    resources :timelines, only: [:index]
  end

  devise_for :users, controllers: { registrations: "registrations" }
  root to: 'pages#home'
  get 'profile', to: 'pages#profile'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/world.rb
class World < ApplicationRecord
  belongs_to :user
  has_many :cards, dependent: :destroy
  has_many :tags, dependent: :destroy

  validates :user, presence: true
  validates :name, presence: true, allow_blank: false

  mount_uploader :photo, PhotoUploader

end

app/controllers/worlds_controller.rb
class WorldsController < ApplicationController
  before_action :set_world, only: [:edit, :update, :destroy]

  def index
    @worlds = World.where(user_id: current_user.id)
  end

  def new
    @world = World.new
    check_permission(@world)
  end

  def create
    @world = World.new(world_params)
    @world.user_id = current_user.id
    if @world.save
      check_permission(@world)
      redirect_to world_cards_path(world_id: @world.id)
    else
      redirect_to new_world_path
    end
  end

  def edit
  end

  def update
    @world.update(world_params)
    check_permission(@world)
    redirect_to worlds_path
  end

  def destroy
    @world.destroy
    check_permission(@world)
    redirect_to worlds_path
  end

  private

  def set_world
    @world = World.find(params[:id])
  end

  def world_params
    params.require(:world).permit(:name, :description, :photo)
  end
end

app/views/worlds/_modal.html.erb
<div class="modal fade" id="<%= name %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= text %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

app/views/worlds/_world_form.html.erb
<%= simple_form_for(@world) do |f| %>
  <div class="container">
    <div>
      <h3 style="color: white"><%= f.label :name %></h3>
      <%= f.text_field :name %>
    </div>
    <div style="margin-top: 10px">
      <h3 style="color: white"><%= f.label :description %></h3>
      <%= f.input :description, label: false, :as => :text, :input_html => { 'rows' => 8} %>
    </div>
    <div style="margin-top: 10px">
      <h3 style="color: white; font-size: 18px"><%= f.input :photo %></h3>
      <%= f.input :photo_cache, as: :hidden%>
    </div>
    <div>
      <h3 style="color: white; font-size: 18px"><%= f.submit class: "btn btn-primary" %></h3>
    </div>
  </div>

<% end %>

app/views/worlds/edit.html.erb
<body class="background">
 <div>
   <h1 class="worldtitle">Edit your world</h1>
   <%= render 'world_form', world: @world %>
  </div>
</body>

app/views/worlds/index.html.erb
<div class="background">
  <div class="container pb-2">
    <h1 class="worldtitle">Your Worlds</h1>

    <%= link_to "Add world", new_world_path, id:"add_world", class: "btn btn-primary" %>

    <div class="worlds">
      <div class="world world-new">
        <div class="world-image" style="background-image:url('https://t4.ftcdn.net/jpg/01/38/57/25/240_F_138572552_0v1vXZOJzU1bR50Uq66mH4cBIRe9g1FX.jpg');">
        </div>
        <div class="world-infos">
          <div class="world-header world-title">
            <h2 id="noneed">New world</h2>
          </div>
          <div class="world-text", id="world-new">
            <p><%= link_to "", new_world_path, class: "fas fa-plus " %></p>
          </div>
        </div>
      </div>
      <% @worlds.each_with_index do |world, index| %>
        <div class="world">
          <div class="world-image" style="background-image:url('<%= cl_image_path world.photo%>');">
          </div>
         <div class="world-infos", data-controller="read">
          <div class="world-header world-title">
            <h2><%= link_to world.name, world_cards_path(world_id: world.id) %></h2>
          </div>
          <div class="world-text">
            <% if (sanitize world.description).bytesize > 400 %>
              <p><%= sanitize world.description[0..400] %>
                <span class="dots"
                      data-target="read.dots">...</span>
                <span class="more"
                      data-target="read.more"><%= sanitize world.description[401..(sanitize world.description).bytesize] %></span>
              </p>
              <% content = sanitize world.description  %>
              <button class="btn btn-link myBtn"
                      class="read_more_btn"
                      data-action="click->read#readMore"
                      data-toggle="modal"
                      data-target="#world<%= index %>"
                      data-index="<%= index %>"
                      data-title="<%= world.name %>">Read more</button>
              <div
                class="hidden-content"
                data-index="<%= index %>"
                style="display: none;"
              ><%= sanitize world.description %></div>
            <% else %>
              <p><%= sanitize world.description %></p>
            <% end %>
          </div>
            <div class="world-footer"
                 data-target="read.buttons">
              <%= link_to "", edit_world_path(world.id), class: "fas fa-edit"  %>
              <%= link_to "", world_path(world.id), method: :delete, class: "fas fa-dumpster-fire" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/worlds/new.html.erb
<body class="background">
 <div>
    <h1 class="worldtitle">Create your world</h1>
    <%= render 'world_form', world: @world %>
  </div>
</body>