config/routes.rb
Rails.application.routes.draw do
  get 'coordinates/new'
  post 'coordinates/create'
  get 'coordinates/update'
  post 'coordinates/destroy'
  post 'coordinates/index'
  post 'timelinks/create'
  post 'timelinks/destroy'
  get '/user', to: "worlds#index", :as => :user_root


  resources :worlds do
    resources :tags, only: [:create, :update]
    resources :cards do
      resources :taggings, only: [:create, :destroy]
    end
    resources :maps
    resources :timelines, only: [:index]
  end

  devise_for :users, controllers: { registrations: "registrations" }
  root to: 'pages#home'
  get 'profile', to: 'pages#profile'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/map.rb
class Map < ApplicationRecord
  has_many :coordinates, dependent: :destroy
  belongs_to :world
  has_one :user, through: :world

  validates :photo, presence: true
  validates :world, presence: true

  mount_uploader :photo, PhotoUploader
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  before_action :set_world, only: [:index, :new, :create]

  def index
    ind = Map.all.where(world_id: params[:world_id])
    maps = []
    ind.each do |map|
      maps.push(map.attributes)
    end
    @map_hash = { maps: maps }
    @cards = Card.where(world_id: params[:world_id])
    # if params[:states].present?
    #   tags = params[:states]
    #   @cards = Card.tag_search(tags)
    # end
    @tags = {tag: @world.tags.map { |e| e.name }}
  end

  def show
  end

  def new
    @map = Map.new()
  end

  def create
    @map = Map.new(map_params)
    @map.world_id = @world.id
    @map.save
    redirect_to world_maps_path
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def set_world
    @world = World.find(params[:world_id])
  end

  def map_params
    params.require(:map).permit(:title, :photo)
  end
end

app/views/maps/_map_form.html.erb
<%= simple_form_for([@world, @map]) do |f| %>
  <div class="container">
    <div>
      <h3 style="color: white"><%= f.label :title %></h3>
      <%= f.text_field :title %>
    </div>

    <div style="margin-top: 10px">
      <h3 style="color: white; font-size: 18px"><%= f.input :photo %></h3>
      <%= f.input :photo_cache, as: :hidden %>
    </div>

  <h3 style="color: white; font-size: 18px"><%= f.submit class: "btn btn-primary"%></h3>

<% end %>

app/views/maps/create.html.erb
<h1>Map#create</h1>
<p>Find me in app/views/map/create.html.erb</p>

app/views/maps/edit.html.erb
<h1>Map#edit</h1>
<p>Find me in app/views/map/edit.html.erb</p>

app/views/maps/index.html.erb
<%= link_to "Add map", new_world_map_path(world_id: @world) %>

<select name="map-select" id="map-select">
  <option value=-1>Select a map</option>
  <% @map_hash[:maps].each do |map| %>
    <option value=<%= map["id"] %>><%= map["title"] %></option>
  <% end %>
  </select>
<button id="delete_marker">Delete marker</button>

<div id="map" data-hash='<%=@map_hash.to_json%>'>
</div>

<% array_of_tag = @tags.to_json %>
<form id="search_bar" action='<%="/worlds/#{@world.id}/maps"%>' name="query" method="get" data-tags='<%= array_of_tag%>'>
  <button id="tag-btn" class="tag-btn">Search</button>
  <div class="marclongdong">
    <select class="js-example-basic-multiple" name="states[]" multiple="multiple" style="width: 75%">
    </select>
  </div>
</form>

<div class="cards">
  <% @cards.each do |card| %>
    <% tag_string = "" %>
    <% card.tags.each do |tag| %>
      <% tag_string += "#{tag.name}," %>
    <% end %>
    <div class="card" data-cardtags="<%= tag_string %>" id="<%= card.id%>" style="height: 40px; min-height:40px; padding: 10px;">
      <h6 class="card-subtitle mb-2 text-muted"><%= card.title %></h6>
    </div>
  <% end %>
</div>

app/views/maps/new.html.erb
<body class="background">
 <div>
    <h1 class="worldtitle">Add a new map</h1>

    <%= render 'map_form', world: @world, map: @map %>
  </div>
</body>

app/views/maps/show.html.erb
<h1>Map#show</h1>
<p>Find me in app/views/map/show.html.erb</p>

app/views/maps/update.html.erb
<h1>Map#update</h1>
<p>Find me in app/views/map/update.html.erb</p>