config/routes.rb
Rails.application.routes.draw do
  get 'coordinates/new'
  post 'coordinates/create'
  get 'coordinates/update'
  post 'coordinates/destroy'
  post 'coordinates/index'
  post 'timelinks/create'
  post 'timelinks/destroy'
  get '/user', to: "worlds#index", :as => :user_root


  resources :worlds do
    resources :tags, only: [:create, :update]
    resources :cards do
      resources :taggings, only: [:create, :destroy]
    end
    resources :maps
    resources :timelines, only: [:index]
  end

  devise_for :users, controllers: { registrations: "registrations" }
  root to: 'pages#home'
  get 'profile', to: 'pages#profile'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_modal.html.erb
<div class="modal fade" id="fuckthisworld" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog card" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title card-header card-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        text
      </div>
      <div class="modal-footer card-footer">
        buttons
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-lg">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"><i class="fas fa-bars"></i></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "home", root_path, :class => "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "about", about_path, :class => "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "contact", contact_path, :class => "nav-link" %>
      </li>
    </ul>
    <div class="login-container">
      <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
          <% if controller.class.name == "CardsController" or controller.class.name == "MapsController" or controller.class.name == "TimelinesController" %>
            <li class="nav-item">
              <%= link_to "notes", world_cards_path, :class => "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "timeline view", world_timelines_path, :class => "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "map view", world_maps_path, :class => "nav-link" %>
            </li>
          <% end %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <img src="https://www.dejohnpetservices.com/wp-content/uploads/cats-animals-kittens-background.jpg" alt="cute af kitten" class="avatar-bordered">
              </a>
              <div class="dropdown-menu">
                <%= link_to "profile", profile_path, :class => "dropdown-item" %>
                <%= link_to "worlds", worlds_path, :class => "dropdown-item" %>
                <%= link_to "log out", destroy_user_session_path, method: :delete, :class => "dropdown-item logout" %>
              </div>
            </li>
        <% else %>
          <button type="button" data-toggle="modal" data-target="#login">
            Log In
          </button>
          <button type="button" data-toggle="modal" data-target="#signup">
            Sign Up
          </button>
        <% end %>
      </ul>
    </div>
  </div>
</div>

<div class="modal fade" id="login" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <%= render 'devise/sessions/new' %>
</div>

<div class="modal fade" id="signup" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <%= render 'devise/registrations/new' %>
</div>