config/routes.rb
Rails.application.routes.draw do
  get 'coordinates/new'
  post 'coordinates/create'
  get 'coordinates/update'
  post 'coordinates/destroy'
  post 'coordinates/index'
  post 'timelinks/create'
  post 'timelinks/destroy'
  get '/user', to: "worlds#index", :as => :user_root


  resources :worlds do
    resources :tags, only: [:create, :update]
    resources :cards do
      resources :taggings, only: [:create, :destroy]
    end
    resources :maps
    resources :timelines, only: [:index]
  end

  devise_for :users, controllers: { registrations: "registrations" }
  root to: 'pages#home'
  get 'profile', to: 'pages#profile'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :world
  has_one :user, through: :world
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings
  has_one :timestamp
  has_one :map
  has_many :coordinates, dependent: :destroy

  validates :world, presence: true

  include PgSearch::Model
  pg_search_scope :search_by_tags,
                  associated_against: {
                    tags: [:name]
                  }

  def self.tag_search(tag_array)
    cards = Card.all
    tag_array.each do |tag|
      sub_cards = Card.search_by_tags(tag)
      cards = cards & sub_cards
    end
    cards
  end

  def self.events_tag_search(tag_array, world_id)
    Card.where(is_event: true, world_id: world_id) & Card.tag_search(tag_array)
  end

  def clean_content
    reg = /^<figure data-trix-attachment="(.)+<\/span><\/figcaption><\/a><\/figure>$/
    self.content.gsub(reg, "")
  end

  def img_content(card_width)
    reg = /<img src="([^ ]+)" width="(\d+)" height="(\d+)">/
    if match = self.content.scan(reg)
      new_string = self.content
      match.each do |match|
        new_string.gsub!(match[0] + "\" width=\"#{match[1]}\" height=\"#{match[2]}\"", match[0] + "\" width=\"#{card_width}\"")
      end
      return new_string
    end
  end

end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]
  before_action :set_world, only: [:index, :show, :new, :edit, :update]

  def index
    @world = World.find(params[:world_id])
    @cards = Card.where(world_id: params[:world_id])
    if params[:states].present?
      tags = params[:states]
      @cards = Card.tag_search(tags)
    end
    @tags = {tag: @world.tags.map { |e| e.name }}
    check_permission(@world)
  end

  def show
  end

  def new
    @card = Card.new()
    check_permission(@world)
  end

  def create
    @world = World.find(params[:world_id])
    @card = Card.new(card_params)
    @card.world_id = params[:world_id]
    @card.content = " " if @card.content.nil?
    @card.save
    check_permission(@world)
    redirect_to edit_world_card_path(world_id: @card.world.id, id: @card.id)
  end

  def edit
    @card = Card.find(params[:id])
    @tagging = Tagging.new()
    check_permission(@world)
  end

  def update
    @card.update(card_params)
    check_permission(@world)
    redirect_to edit_world_card_path(world_id: @card.world.id, id: @card.id)
  end

  def destroy
    @world = World.find(params[:world_id])
    @card.destroy
    check_permission(@world)
    redirect_to world_cards_path(params[:world_id])
  end

  private

  def set_card
    @card = Card.find(params[:id])
  end

  def set_world
    @world = World.find(params[:world_id])
  end

  def card_params
    params.require(:card).permit(:title, :content, :is_event)
  end
end

app/views/cards/_card_form.html.erb
<%= simple_form_for([@world, @card]) do |f| %>
  <div style="margin-bottom: 10px">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <%= f.label :content %>
  <%= f.trix_editor :content %>
  <%= f.input :is_event, as: :boolean %>
  <div style="margin-top: 10px">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/cards/_tag_form.html.erb
<%= simple_form_for([world, card, tagging], remote: true) do |f| %>
  <div class="container" style="background-color: white">
    <div id="search-tag-form">
      <%= f.association :tag, collection: world.tags.order(:name) %>
    </div>
    <div id="add-tag-form" class="hide-div" >
        <%= simple_fields_for :other do |o| %>
          <%= o.input :name, as: :string, label: 'tag'%>
       <% end %>
    </div>
    <div id="switch_button">
      <button id="button-add-new-tag">Create tag</button>
      <button id="button-search-new-tag" class="hide-div">Return</button>
    </div>
    <div style="margin-top: 20px; padding-bottom: 20px">
      <%= f.submit value="Add tag" %>
    </div>
  </div>
<% end %>

app/views/cards/_tagging_item.html.erb
<div id=<%="tagging-#{tagging.id}"%> >
  <%= "##{tagging.tag.name.gsub(" ", "_")}" %>
  <%= link_to "X", world_card_tagging_path(world_id: @world.id, card_id: @card.id, id: tagging.id), method: :delete, remote: true %>
</div>

app/views/cards/_title_form.html.erb
<%= simple_form_for([@world, @card]) do |f| %>
  <div class="container">
    <div>
      <h3 style="color: white"><%= f.label :title %></h3>
      <%= f.text_field :title %>
    </div>
    <div style="padding-top: 20px">
      <%= f.submit class: "btn btn-primary"%>
    </div>
  </div>


<% end %>

app/views/cards/edit.html.erb
<body class="background">
  <h1 class="worldtitle">Edit your card</h1>

  <div class="container" style="background-color: white; padding-top: 10px">
    <%= render 'card_form', world: @world, card: @card %>
  </div>

  <div class="text-muted container" style="background-color: white; padding-top: 15px; padding-bottom: 15px">
    <% @card.taggings.each do |tagging| %>
      <%= render 'tagging_item', tagging: tagging %>
    <% end %>
  </div>
  <div id="tag_form_wrap" style="margin-bottom: 20px">
    <%= render 'tag_form', world: @world, card: @card, tagging: @tagging %>
  </div>
</body>

app/views/cards/index.html.erb
<div class="background">
<div class="banner-world" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= @world.photo.url %>); height: 16vh;">
  <div class="container", data-controller="read">
    <h1><%= sanitize @world.name %></h1>
    <% if (sanitize @world.description).bytesize > 240 %>
      <p><span class="less" data-target="read.less"><%= sanitize @world.description[0..240] %></span>
        <span class="dots"
            data-target="read.dots">...</span>
        <span class="more"
            data-target="read.more"><%= sanitize @world.description %></span>
      </p>

        <button class="btn btn-link myBtn"
                      class="read_more_btn"
                      data-action="click->read#readMore"
                      data-toggle="modal"
                      data-title="<%= @world.name %>">Read more</button>
        <div
          class="hidden-content"
          style="display: none;"
        ><%= sanitize sanitize @world.description  %></div>
    <% else %>
      <p><%= sanitize @world.description %></p>
    <% end %>
    <div class="world-link"
         data-target="read.buttons">
      <%= link_to "Edit World", edit_world_path(@world.id), class: "btn btn-primary"  %>
      <%= link_to "Back to worlds", worlds_path, class: "btn btn-primary" %>
    </div>
   </div>
</div>
<% array_of_tag = @tags.to_json %>

<form id="search_bar" action='<%="/worlds/#{@world.id}/cards"%>' name="query" method="get" data-tags='<%= array_of_tag%>' class="container">
  <input type="submit" id="search-button" class="btn btn-primary" value="Search">
  <div class="marclongdong">
    <select class="js-example-basic-multiple" name="states[]" multiple="multiple" style="width: 100%">
    </select>
  </div>
  </form>

<div class="container pb-2">
  <div class="cards">

    <div class="card card-new">
      <h5 class="card-header card-title">New note</h5>
      <div class="card-body new-card">
        <%= link_to "", new_world_card_path(world_id: @world.id), class:"fas fa-plus" %>
      </div>
    </div>
    <% @cards.each_with_index do |card, index| %>
      <div class="card"
           data-controller="read">
        <h5 class="card-header card-title"><%= card.title %></h5>
        <div class="card-body">
          <h6 class="card-subtitle mb-2 text-muted"
              data-target="read.tags">
          <% card.tags.each do |tag| %>
            <%= "##{tag.name.gsub(" ", "_")}" %>
          <% end %></h6>
            <% if (sanitize card.content).bytesize > 240 || card.content != card.clean_content %>

              <p class="card-text">
                <div class="less" data-target="read.less"><%= sanitize card.clean_content[0..240] %>
                </div>
                <span class="dots" data-target="read.dots">...</span>
                <span class="more" data-target="read.more">
                  <%= sanitize card.img_content("100%") %>
                </span>
              </p>
              <button class="btn btn-link myBtn"
                      data-action="click->read#readMore"
                      data-toggle="modal"
                      data-target="#modal<%= index %>"
                      data-title="<%= card.title %>"
                      data-index="<%= index %>">Read more</button>
              <div
                class="hidden-content"
                data-index="<%= index %>"
                style="display: none;"
              ><%= sanitize card.content %></div>
            <% else %>
              <p class="card-text"><%= sanitize card.clean_content %></p>
            <% end %>
        </div>
        <div class="card-footer"
              data-target="read.buttons">
          <%= link_to "", edit_world_card_path(world_id: card.world.id, id: card.id), class: "fas fa-edit"  %>
          <%= link_to "", world_card_path(world_id: card.world.id, id: card.id), method: :delete, class: "fas fa-dumpster-fire" %>
        </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<!--  if bytesize of content is >100 char
        a = card.content[0..100]
        b = card.content[101..a.bytesize] -->

app/views/cards/new.html.erb
<body class="background">
 <div>
    <h1 class="worldtitle">Create a new card</h1>
    <%= render 'title_form', world: @world, card: @card %>
  </div>
</body>

app/views/cards/show.html.erb
<h1>Cards#show</h1>
<p>Find me in app/views/cards/show.html.erb</p>

app/views/cards/update.js.erb
const button = document.getElementById("save");
const content = document.getElementById("x");
console.log("BBBBBBBBBBBBBBBBBB");
// button.addEventListener("click", (event) => {
//   event.preventDefault();
//   console.log("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
//   content.editor.insertString("Hello");
// });

<% if @card.errors.any? %>
  button.value = "1";
<% else %>
  button.value = "2";
<% end %>